import { memo } from "react";
import type { ChatMessage, ChangedFile } from "../types";
import { UserMessage } from "./UserMessage";
import { AssistantMessage } from "./AssistantMessage";
import { SystemMessage } from "./SystemMessage";
import { ResultMessage } from "./ResultMessage";

interface MessageBubbleProps {
  message: ChatMessage;
  prevMessage?: ChatMessage;
  toolStates: Record<string, "expanded" | "collapsed">;
  onToggleTool: (id: string, isCurrentlyExpanded: boolean) => void;
  isLastMessage: boolean;
  onEdit?: (messageId: string) => void;
  onFork?: (messageId: string) => void;
  onRetry?: (messageId: string) => void;
  onCopy?: (messageId: string) => void;
  planContent?: string;
  onNavigateToSession?: (sessionId: string) => void;
  modifiedFiles?: ChangedFile[];
  onOpenFile?: (filePath: string, diff: string) => void;
}

export const MessageBubble = memo(function MessageBubble({
  message,
  prevMessage,
  toolStates,
  onToggleTool,
  isLastMessage,
  onEdit,
  onFork,
  onRetry,
  onCopy,
  planContent,
  onNavigateToSession,
  modifiedFiles,
  onOpenFile,
}: MessageBubbleProps) {
  if (message.type === "user") {
    // Detect if this user message was generated by a Skill tool expansion
    const skillName = (() => {
      if (!prevMessage || prevMessage.type !== "assistant") return undefined;
      const blocks = Array.isArray(prevMessage.content) ? prevMessage.content : [];
      const skillBlock = blocks.find(b => b.type === "tool_use" && b.name === "Skill");
      if (!skillBlock) return undefined;
      return (skillBlock.input as { skill?: string } | undefined)?.skill ?? "skill";
    })();
    return (
      <UserMessage
        message={message}
        onEdit={onEdit}
        onFork={onFork}
        onRetry={onRetry}
        onCopy={onCopy}
        planContent={planContent}
        skillName={skillName}
      />
    );
  }

  if (message.type === "system") {
    return <SystemMessage message={message} onNavigateToSession={onNavigateToSession} />;
  }

  if (message.type === "error") {
    const content = Array.isArray(message.content) ? message.content : [];
    return (
      <div className="px-3 py-2 bg-red-500/10 border border-red-500/20 rounded-lg text-sm text-red-400">
        {content[0]?.text || "Unknown error"}
      </div>
    );
  }

  if (message.type === "result") {
    return (
      <ResultMessage
        message={message}
        modifiedFiles={modifiedFiles}
        onOpenFile={onOpenFile}
      />
    );
  }

  // Assistant message
  return (
    <AssistantMessage
      message={message}
      toolStates={toolStates}
      onToggleTool={onToggleTool}
      isLastMessage={isLastMessage}
      planContent={planContent}
    />
  );
});
